workflow:
    rules:
        - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
        - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"

image: python:3.12

stages:
    - build
    - test

build:
    stage: build
    script:
        - pip install -r requirements_tests.txt
    services:
        - postgres:latest
    variables:
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_pwd
    cache:
        key: pip-cache
        paths:
            - .cache/pip
    tags:
        - students

pytest:
    stage: test
    dependencies:
        - build
    script:
        - pytest tests
    tags:
        - students

black:
    stage: test
    dependencies:
        - build
    script:
        - black --diff --check .
    tags:
        - students

isort:
    stage: test
    dependencies:
        - build
    script:
        - isort --check-only --diff --profile black .
    tags:
        - students

flake8:
    stage: test
    dependencies:
        - build
    script:
        - flake8 .
    tags:
        - students

mypy:
    stage: test
    dependencies:
        - build
    script:
        - mypy .
    tags:
        - students