workflow:
    rules:
        - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
        - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"

image: python:3.12

stages:
    - build
    - test

cache:
    key: pip-cache
    paths:
        - $CI_PROJECT_DIR/.cache/pip

before_script:
    - mkdir -p $CI_PROJECT_DIR/.cache/pip

build-app:
    stage: build
    script:
        - pip install -r requirements_tests.txt
    services:
        - postgres:latest
    variables:
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_pwd    
    cache:
        paths:
            - /usr/local/bin/
        policy: push
    tags:
        - students

pytest:
    stage: test
    script:
        - pytest tests
    tags:
        - students

black:
    stage: test
    script:
        - black --diff --check .
    tags:
        - students

isort:
    stage: test
    script:
        - isort --check-only --diff --profile black .
    tags:
        - students

flake8:
    stage: test
    script:
        - flake8 .
    tags:
        - students

mypy:
    stage: test
    script:
        - mypy .
    tags:
        - students