workflow:
    rules:
        - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
        - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"

image: python:3.12

stages:
    - build
    - test

default:
    cache:
        key: pip-cache
        paths:
            - .cache/pip
        policy: push
    before_script:
        - python -V
        - pip install virtualenv
        - virtualenv .venv
        - source .venv/bin/activate
        - pip install -r requirements_tests.txt
    tags:
        - students

pytest:
    stage: test
    services:
        - postgres:latest
    variables:
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_pwd
    script:
        - export PYTHONPATH=$PYTHONPATH:/src
        - python3 -m pytest tests
    tags:
        - students

black:
    stage: test
    services:
        - postgres:latest
    variables:
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_pwd
    script:
        - python3 -m black --diff --check src
        - python3 -m black --diff --check tests
    tags:
        - students

isort:
    stage: test
    services:
        - postgres:latest
    variables:
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_pwd
    script:
        - python3 -m isort --check-only --diff --profile black src
        - python3 -m isort --check-only --diff --profile black tests
    tags:
        - students

flake8:
    stage: test
    services:
        - postgres:latest
    variables:
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_pwd
    script:
        - python3 -m flake8 src
        - python3 -m flake8 tests
    tags:
        - students

mypy:
    stage: test
    services:
        - postgres:latest
    variables:
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_pwd
    script:
        - python3 -m mypy src
        - python3 -m mypy tests
    tags:
        - students