workflow:
    rules:
        - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
        - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
    - build
    - test

build-app:
    stage: build
    image: python:3.12
    script:
        - pip install -r requirements_tests.txt
    services:
        - postgres:latest
    variables:
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_pwd
    artifacts:
        when: on_success
        expire_in: 1 hour
        paths:
            - .artefacts/
    tags:
        - students

pytest:
    stage: test
    script:
        - pytest tests
    tags:
        - students

black:
    stage: test
    script:
        - black --diff --check .
    tags:
        - students

isort:
    stage: test
    script:
        - isort --check-only --diff --profile black .
    tags:
        - students

flake8:
    stage: test
    script:
        - flake8 .
    tags:
        - students

mypy:
    stage: test
    script:
        - mypy .
    tags:
        - students