workflow:
    rules:
        - if: $CI_COMMIT_BRANCH == "master"
        - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"

image: python:3.12

stages:
    - test

black:
    stage: test
    before_script:
        - python -V
        - pip install virtualenv
        - virtualenv .venv
        - source .venv/bin/activate
        - pip install -r requirements_tests.txt
    script:
        - python3 -m black --diff --check src
        - python3 -m black --diff --check tests
    tags:
        - students

isort:
    stage: test
    before_script:
        - python -V
        - pip install virtualenv
        - virtualenv .venv
        - source .venv/bin/activate
        - pip install -r requirements_tests.txt
    script:
        - python3 -m isort --check-only --diff --profile black src
        - python3 -m isort --check-only --diff --profile black tests
    tags:
        - students

flake8:
    before_script:
        - python -V
        - pip install virtualenv
        - virtualenv .venv
        - source .venv/bin/activate
        - pip install -r requirements_tests.txt
    stage: test
    script:
        - python3 -m flake8 src
        - python3 -m flake8 tests
    tags:
        - students

mypy:
    before_script:
        - python -V
        - pip install virtualenv
        - virtualenv .venv
        - source .venv/bin/activate
        - pip install -r requirements_tests.txt
    stage: test
    script:
        - python3 -m mypy src
        - python3 -m mypy tests
    tags:
        - students