workflow:
    rules:
        - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
        - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"

image: python:3.12

stages:
    - build
    - test

build-app:
    stage: build
    script:
        - pip install -r requirements_tests.txt
    services:
        - postgres:latest
    variables:
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_pwd    
    cache:
        paths:
            - /usr/local/bin/
        policy: push
    tags:
        - students

pytest:
    stage: test
    script:
        - python3 -m pytest tests
    tags:
        - students
    cache:
        paths:
            - project-venv
        policy: pull

black:
    stage: test
    script:
        - python3 -m black --diff --check .
    tags:
        - students
    cache:
        paths:
            - /usr/local/bin/
        policy: pull

isort:
    stage: test
    script:
        - python3 -m isort --check-only --diff --profile black .
    tags:
        - students
    cache:
        paths:
            - /usr/local/bin/
        policy: pull

flake8:
    stage: test
    script:
        - python3 -m flake8 .
    tags:
        - students
    cache:
        paths:
            - /usr/local/bin/
        policy: pull

mypy:
    stage: test
    script:
        - python3 -m mypy .
    tags:
        - students
    cache:
        paths:
            - /usr/local/bin/
        policy: pull