workflow:
    only:
        - master
        - merge request
        - push

stages:
    - build
    - test

build-app:
    stage: build
    image: python:3.12
    script:
        - pip install -r requirements_test.txt
    services:
        - postgres:latest
    variables:
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_pwd
    artifacts:
        untracked: false
        when: on_success
        expire_in: 1 hour
        paths:
            - ./

pytest:
    stage: test
    script:
        - pytest tests

black:
    stage: test
    script:
        - black --diff --check .

isort:
    stage: test
    script:
        - isort --check-only --diff --profile black .

flake8:
    stage: test
    script:
        - flake8 .

mypy:
    stage: test
    script:
        - mypy .

