FROM python:3.12


COPY requirements.txt ./requirements.txt

ENV OYTHONPATH=./src
RUN pip install -r requirements.txt
COPY ./src ./src

CMD ["python3", "./src/main."]

services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data