"""Image.tweet_id now is nullable

Revision ID: a35905adef8c
Revises: 28aa896b019f
Create Date: 2024-09-11 14:33:00.499834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35905adef8c'
down_revision: Union[str, None] = '28aa896b019f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'tweet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'tweet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
