services:
  postgres:
    image: postgres:13.3
    environment:
      # DEBUG
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data